### ISSUE TITLE
.follow does not follow urls with unicode characters

### ISSUE THREAD

**Issue by deathg0d** [rchipka/node-osmosis#113]
Osmosis ends without any result if it is set to follow urls with unicode characters, ex: 'a@href' where href looks something like "http://some website .com/समाज-विश्व"

**Comment by miladkdz** [comment]
Have the same issue here. I found the rewrite() command which was deprecated so I used find().get(callback)

**Comment by deathg0d** [comment]
@miladkdz thanks for the reply. I am unable to use find get. I don't think get has a callback. Does it? Do you have a little more detail on how you used it? Thanks!

**Comment by miladkdz** [comment]
@deathg0d No problem :)
if you look at the source code for the get command (https://github.com/rchipka/node-osmosis/blob/master/lib/commands/get.js#L10) you can see. And here is an example where I selected an element with href attribute and modify the url:

   .find('h2.header a')
    .get(function(url, obj){
        var nextPage = url.getAttribute('href').substring(1);
        return '/' + nextPage.substring(0, nextPage.indexOf('/')) + '/'
        + encodeURIComponent(nextPage.substring(nextPage.indexOf('/')));
    })

**Comment by rchipka** [comment]
Fixed in 1.1.0

**Comment by deathg0d** [comment]
@rchipka I have updated to 1.1.0  but I don't think it's fixed. Following a unicode url gives me a "400 Bad Request"
